# Generated by Django 3.1.4 on 2020-12-27 20:07

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[profiles.models.validate_max]),
        ),
    ]
