# Generated by Django 3.1.4 on 2021-01-14 10:00

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_herolevels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herolevels',
            name='level_data',
            field=jsonfield.fields.JSONField(),
        ),
    ]
