# Generated by Django 3.1.4 on 2021-01-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210114_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='herolevels',
            name='general_level',
            field=models.DecimalField(decimal_places=0, default=50, max_digits=2),
        ),
    ]
