# Generated by Django 3.1.4 on 2020-12-21 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20201221_2227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
