# Generated by Django 3.1.4 on 2020-12-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20201227_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=4, max_length=2),
        ),
    ]
