# Generated by Django 3.1.4 on 2020-12-21 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_usersprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersProfile',
        ),
    ]
