# Generated by Django 3.1.4 on 2020-12-27 21:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20201227_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(300)]),
        ),
    ]
