# Generated by Django 3.1.4 on 2021-01-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_groupselect'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='share',
            field=models.BooleanField(default=True),
        ),
    ]
