# Generated by Django 3.1.4 on 2021-01-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_customgroup_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
