# Generated by Django 3.1.4 on 2021-01-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_customgroup_users_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='share',
            field=models.BooleanField(default=False),
        ),
    ]
