# Generated by Django 3.1.4 on 2020-12-26 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wod_name', models.CharField(default='WOD', max_length=100)),
                ('ft_result', models.DurationField(blank=True)),
                ('amrap_result', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('mw_result', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('rx', models.BooleanField(default=True)),
                ('user_comment', models.TextField(blank=True, null=True)),
                ('member_comment', models.TextField(blank=True, null=True)),
                ('wod_date', models.DateTimeField(default=datetime.datetime.now)),
                ('personal_record', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(default='', max_length=40)),
                ('workout_type', models.CharField(choices=[('FT', 'For Time'), ('AMRAP', 'As Many Rounds As Possible'), ('MW', 'Max. Weight')], max_length=5)),
                ('workout_category', models.CharField(choices=[('PL', 'Power Lifts'), ('OL', 'Olympic Lifts'), ('SP', 'Speed'), ('EN', 'Endurance'), ('BW', 'Body Weight'), ('HE', 'Heavy'), ('LI', 'Light'), ('LO', 'Long')], max_length=5)),
                ('description', models.TextField()),
            ],
        ),
    ]
