# Generated by Django 3.1.4 on 2021-01-03 16:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wod_name', models.CharField(default='WOD', max_length=100)),
                ('ft_result', models.DurationField(null=True)),
                ('amrap_result', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mw_result', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rx', models.BooleanField(blank=True, default=True)),
                ('user_comment', models.TextField(blank=True, null=True)),
                ('member_comment', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('personal_record', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(default='', max_length=40)),
                ('workout_type', models.CharField(choices=[('FT', 'For Time'), ('AMRAP', 'As Many Rounds As Possible'), ('MW', 'Max. Weight')], max_length=5)),
                ('workout_category', models.CharField(choices=[('PL', 'Power Lifts'), ('OL', 'Olympic Lifts'), ('SP', 'Speed'), ('EN', 'Endurance'), ('BW', 'Body Weight'), ('HE', 'Heavy'), ('LI', 'Light'), ('LO', 'Long')], max_length=5)),
                ('description', models.TextField()),
                ('workout_is_wod', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MemberComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=250)),
                ('log_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='workouts.log')),
                ('member', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
