# Generated by Django 3.1.4 on 2020-12-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workouts',
            new_name='Workout',
        ),
    ]
