# Generated by Django 3.1.4 on 2021-01-03 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='workout_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='workouts.workout'),
        ),
    ]
