# Generated by Django 3.1.4 on 2020-12-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20201224_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ft_result', models.DurationField(blank=True)),
            ],
        ),
    ]
