# Generated by Django 3.1.4 on 2021-01-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_log_workout_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='workout_id',
            new_name='workout',
        ),
    ]
