# Generated by Django 3.1.4 on 2020-12-25 22:20

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0003_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='amrap_result',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='log',
            name='member_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='mw_result',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='log',
            name='personal_record',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='log',
            name='rx',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='log',
            name='user_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='wod_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
