# Generated by Django 3.1.4 on 2021-01-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_auto_20210103_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='wod_name',
        ),
    ]
