# Generated by Django 3.1.4 on 2020-12-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_auto_20201225_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='user_comment',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
