# Generated by Django 3.1.4 on 2020-12-26 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_auto_20201226_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='wod_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
