# Generated by Django 3.1.4 on 2020-12-26 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_auto_20201226_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='wod_date',
            new_name='date',
        ),
    ]
