# Generated by Django 3.1.4 on 2020-12-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_auto_20201226_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='ft_result',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
