# Generated by Django 3.1.4 on 2020-12-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_auto_20201226_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='ft_result',
            field=models.DurationField(default='00:00', null=True),
        ),
    ]
