# Generated by Django 3.1.4 on 2020-12-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_auto_20201227_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='amrap_result',
            field=models.DecimalField(blank=True, decimal_places=2, default='number of rounds', max_digits=5),
        ),
        migrations.AlterField(
            model_name='log',
            name='mw_result',
            field=models.DecimalField(blank=True, decimal_places=2, default="weight in kg's", max_digits=5),
        ),
    ]
