# Generated by Django 3.1.4 on 2020-12-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_auto_20201227_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='amrap_result',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='log',
            name='mw_result',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
