# Generated by Django 3.1.4 on 2020-12-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0011_auto_20201227_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='workout_is_wod',
            field=models.BooleanField(default=False),
        ),
    ]
