# Generated by Django 3.1.4 on 2020-12-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0012_workout_workout_is_wod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='rx',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
